import 'server-only';
import type { TemplateDetail, TemplateType, LanguageCode } from '@/types/template';

export interface TemplateSeed extends Omit<TemplateDetail, 'category'> {
  categoryId: string;
  categorySlug: string;
  categoryName: string;
}

const NOW = '2026-06-01T00:00:00.000Z';
const SAMPLE_VIDEO = 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4';

function common(idx: number) {
  const created = new Date(Date.parse('2026-01-01') + idx * 86400000 * 5).toISOString();
  return {
    status: 'PUBLISHED' as const,
    visibility: 'PUBLIC' as const,
    createdAt: created,
    updatedAt: NOW,
  };
}

export const templateSeed: TemplateSeed[] = [
  {
    id: 'tpl_royal_mandap_gold', slug: 'royal-mandap-gold', name: 'Royal Mandap Gold',
    categoryId: 'cat_wedding', categorySlug: 'wedding', categoryName: 'Wedding',
    type: 'VIDEO' as TemplateType, language: 'EN' as LanguageCode,
    thumbnail: 'https://images.unsplash.com/photo-1770757685390-ecdfac51d95e',
    demoPreviewUrl: SAMPLE_VIDEO,
    description: 'Cinematic mandap reveal with gold-foil monogram, falling petals and live calligraphy of the couple’s names. Ideal for traditional Indian weddings.',
    tags: ['gold', 'mandap', 'royal', 'cinematic'],
    features: ['HD 1080p video', 'Gold-foil monogram', 'Editable bride / groom names', 'Background sehnai music', 'Save-the-date variation'],
    seoTitle: 'Royal Mandap Gold — Wedding Invitation Video',
    seoDescription: 'Cinematic gold mandap wedding invitation video template.',
    seoKeywords: 'wedding video invitation, mandap, gold',
    featured: true, trending: false, bestSeller: false,
    ...common(0),
  },
  {
    id: 'tpl_mehendi_mosaic', slug: 'mehendi-mosaic', name: 'Mehendi Mosaic',
    categoryId: 'cat_wedding', categorySlug: 'wedding', categoryName: 'Wedding',
    type: 'VIDEO', language: 'HI',
    thumbnail: 'https://images.unsplash.com/photo-1612611450433-360c82a57e01',
    demoPreviewUrl: SAMPLE_VIDEO,
    description: 'Moody mehendi-night invitation with henna pattern reveal and Hindi typography. Perfect for sangeet and mehendi functions.',
    tags: ['mehendi', 'sangeet', 'henna'],
    features: ['HD 1080p video', 'Hindi typography', 'Henna pattern animation', 'Couple monogram'],
    seoTitle: 'मेहंदी मोजाइक — विवाह निमंत्रण वीडियो',
    seoDescription: 'Mehendi sangeet invitation video template in Hindi.',
    seoKeywords: 'मेहंदी, संगीत, विवाह निमंत्रण',
    featured: false, trending: true, bestSeller: false,
    ...common(1),
  },
  {
    id: 'tpl_pastel_bloom', slug: 'pastel-bloom', name: 'Pastel Bloom',
    categoryId: 'cat_engagement', categorySlug: 'engagement', categoryName: 'Engagement',
    type: 'PDF_SINGLE', language: 'EN',
    thumbnail: 'https://images.unsplash.com/photo-1544137469-e45be1c41f7a',
    demoPreviewUrl: null,
    description: 'Single-page pastel bloom engagement invitation — watercolour florals, hand-lettered script and gentle blush palette.',
    tags: ['pastel', 'floral', 'minimal'],
    features: ['Single A5 PDF', 'Print-ready 300 DPI', 'Editable date and venue', 'Watercolour florals'],
    seoTitle: 'Pastel Bloom Engagement Invitation PDF',
    seoDescription: 'Pastel floral engagement invitation, print-ready PDF template.',
    seoKeywords: 'engagement invitation, pastel, floral',
    featured: false, trending: false, bestSeller: false,
    ...common(2),
  },
  {
    id: 'tpl_vintage_roses', slug: 'vintage-roses', name: 'Vintage Roses',
    categoryId: 'cat_engagement', categorySlug: 'engagement', categoryName: 'Engagement',
    type: 'VIDEO', language: 'EN',
    thumbnail: 'https://images.unsplash.com/photo-1633037773384-27d7ac0491e7',
    demoPreviewUrl: SAMPLE_VIDEO,
    description: 'Antique-rose engagement reel with vintage paper textures and slow camera push on the couple monogram.',
    tags: ['vintage', 'roses', 'romantic'],
    features: ['HD 1080p video', 'Vintage paper textures', 'Live monogram reveal', 'Soft piano score'],
    seoTitle: 'Vintage Roses Engagement Invitation Video',
    seoDescription: 'Antique-rose engagement video template.',
    seoKeywords: 'engagement video invitation, vintage, roses',
    featured: false, trending: false, bestSeller: true,
    ...common(3),
  },
  {
    id: 'tpl_confetti_pop', slug: 'confetti-pop', name: 'Confetti Pop',
    categoryId: 'cat_birthday', categorySlug: 'birthday', categoryName: 'Birthday',
    type: 'VIDEO', language: 'EN',
    thumbnail: 'https://images.unsplash.com/photo-1530103862676-de8c9debad1d',
    demoPreviewUrl: SAMPLE_VIDEO,
    description: 'Colourful confetti burst birthday invitation — bouncing balloons, exploding sparkles and a big number reveal.',
    tags: ['birthday', 'confetti', 'colourful'],
    features: ['HD 1080p video', 'Editable age + name', 'Balloon burst animation', 'Upbeat soundtrack'],
    seoTitle: 'Confetti Pop — Birthday Video Invitation',
    seoDescription: 'Colourful animated birthday invitation video.',
    seoKeywords: 'birthday video invitation, confetti, colourful',
    featured: true, trending: false, bestSeller: false,
    ...common(4),
  },
  {
    id: 'tpl_magical_unicorn', slug: 'magical-unicorn', name: 'Magical Unicorn',
    categoryId: 'cat_birthday', categorySlug: 'birthday', categoryName: 'Birthday',
    type: 'PDF_MULTI', language: 'EN',
    thumbnail: 'https://images.unsplash.com/photo-1528459801416-a9e53bbf4e17',
    demoPreviewUrl: null,
    description: 'A 4-page unicorn birthday suite — main invitation, RSVP, schedule and thank-you card. Pastel rainbow aesthetic.',
    tags: ['unicorn', 'kids', 'rainbow'],
    features: ['4 print-ready PDFs', 'Pastel rainbow theme', 'Editable kid’s name + age', '300 DPI bleed area'],
    seoTitle: 'Magical Unicorn Birthday Invitation Suite',
    seoDescription: 'Pastel unicorn kids birthday invitation PDF suite.',
    seoKeywords: 'kids birthday invitation, unicorn, pdf',
    featured: false, trending: false, bestSeller: false,
    ...common(5),
  },
  {
    id: 'tpl_sweet_sixteen', slug: 'sweet-sixteen', name: 'Sweet Sixteen',
    categoryId: 'cat_birthday', categorySlug: 'birthday', categoryName: 'Birthday',
    type: 'VIDEO', language: 'EN',
    thumbnail: 'https://images.unsplash.com/photo-1559455208-f82921450174',
    demoPreviewUrl: SAMPLE_VIDEO,
    description: 'Pastel disco-themed sweet sixteen invitation video with shimmer transitions and editable photo placeholders.',
    tags: ['teen', 'sweet sixteen', 'disco'],
    features: ['HD 1080p video', 'Editable photo placeholders', 'Shimmer transitions', 'Pop soundtrack'],
    seoTitle: 'Sweet Sixteen Birthday Invitation Video',
    seoDescription: 'Pastel disco sweet-sixteen birthday invitation video.',
    seoKeywords: 'sweet sixteen, birthday video, teen birthday',
    featured: false, trending: false, bestSeller: false,
    ...common(6),
  },
  {
    id: 'tpl_forever_promise', slug: 'forever-promise', name: 'Forever Promise',
    categoryId: 'cat_anniversary', categorySlug: 'anniversary', categoryName: 'Anniversary',
    type: 'PDF_SINGLE', language: 'EN',
    thumbnail: 'https://images.unsplash.com/photo-1632610992723-82d7c212f6d7',
    demoPreviewUrl: null,
    description: 'Minimal black-and-white anniversary invitation with foiled monogram — modern, editorial and timeless.',
    tags: ['minimal', 'monochrome', 'editorial'],
    features: ['Single A5 PDF', 'Foiled monogram', 'Editorial layout', 'Editable years celebrated'],
    seoTitle: 'Forever Promise Anniversary Invitation',
    seoDescription: 'Minimal monochrome anniversary invitation PDF.',
    seoKeywords: 'anniversary invitation, minimal, monochrome',
    featured: false, trending: false, bestSeller: false,
    ...common(7),
  },
  {
    id: 'tpl_silver_jubilee', slug: 'silver-jubilee', name: 'Silver Jubilee',
    categoryId: 'cat_anniversary', categorySlug: 'anniversary', categoryName: 'Anniversary',
    type: 'VIDEO', language: 'HI',
    thumbnail: 'https://images.unsplash.com/photo-1710587384897-b1390bd46cc6',
    demoPreviewUrl: SAMPLE_VIDEO,
    description: 'Vibrant 25th anniversary celebration video with floral suite reveal and Hindi typography.',
    tags: ['25 years', 'floral', 'celebration'],
    features: ['HD 1080p video', 'Hindi typography', 'Floral suite reveal', 'Editable years + names'],
    seoTitle: 'रजत जयंती — वर्षगांठ निमंत्रण वीडियो',
    seoDescription: '25वीं वर्षगांठ निमंत्रण वीडियो टेम्प्लेट.',
    seoKeywords: 'रजत जयंती, वर्षगांठ',
    featured: false, trending: true, bestSeller: false,
    ...common(8),
  },
  {
    id: 'tpl_golden_years', slug: 'golden-years', name: 'Golden Years',
    categoryId: 'cat_anniversary', categorySlug: 'anniversary', categoryName: 'Anniversary',
    type: 'VIDEO', language: 'EN',
    thumbnail: 'https://images.unsplash.com/photo-1525773727385-12f7f5a8f02a',
    demoPreviewUrl: SAMPLE_VIDEO,
    description: 'Rustic kraft-paper 50th anniversary invitation video with sepia photo montage and acoustic score.',
    tags: ['50 years', 'rustic', 'kraft'],
    features: ['HD 1080p video', 'Sepia photo montage', 'Acoustic score', 'Editable years celebrated'],
    seoTitle: 'Golden Years — 50th Anniversary Video Invitation',
    seoDescription: '50th anniversary kraft-paper invitation video.',
    seoKeywords: '50th anniversary, golden jubilee, rustic',
    featured: false, trending: false, bestSeller: true,
    ...common(9),
  },
  {
    id: 'tpl_diya_glow', slug: 'diya-glow', name: 'Diya Glow',
    categoryId: 'cat_house_warming', categorySlug: 'house-warming', categoryName: 'House Warming',
    type: 'VIDEO', language: 'HI',
    thumbnail: 'https://images.unsplash.com/photo-1738025275088-554086913a78',
    demoPreviewUrl: SAMPLE_VIDEO,
    description: 'Warm griha pravesh invitation with glowing diyas, golden particles and Sanskrit shlokas.',
    tags: ['griha pravesh', 'diya', 'sacred'],
    features: ['HD 1080p video', 'Sanskrit shloka opening', 'Diya glow animation', 'Editable address + date'],
    seoTitle: 'दीया ग्लो — गृह प्रवेश निमंत्रण',
    seoDescription: 'गृह प्रवेश निमंत्रण वीडियो टेम्प्लेट.',
    seoKeywords: 'गृहप्रवेश, दीया, निमंत्रण',
    featured: true, trending: false, bestSeller: false,
    ...common(10),
  },
  {
    id: 'tpl_modern_welcome', slug: 'modern-welcome', name: 'Modern Welcome',
    categoryId: 'cat_house_warming', categorySlug: 'house-warming', categoryName: 'House Warming',
    type: 'PDF_SINGLE', language: 'EN',
    thumbnail: 'https://images.unsplash.com/photo-1732649124686-3bab54f79aa3',
    demoPreviewUrl: null,
    description: 'Crisp modern housewarming invitation with line-art house and tasteful typography. Print-ready PDF.',
    tags: ['modern', 'minimal', 'line-art'],
    features: ['Single A5 PDF', 'Print-ready 300 DPI', 'Line-art house illustration', 'Editable address + date'],
    seoTitle: 'Modern Welcome Housewarming Invitation',
    seoDescription: 'Modern minimal housewarming invitation PDF template.',
    seoKeywords: 'housewarming invitation, modern, minimal',
    featured: false, trending: false, bestSeller: false,
    ...common(11),
  },
];
