export const adminRoutes = {
  dashboard: '/admin',
  categories: '/admin/categories',
  categoryNew: '/admin/categories/new',
  categoryEdit: (id: string) => `/admin/categories/${id}`,
  templates: '/admin/templates',
  templateNew: '/admin/templates/new',
  templateEdit: (id: string) => `/admin/templates/${id}`,
  templateFields: '/admin/template-fields',
  templateFieldEdit: (id: string) => `/admin/template-fields/${id}`,
  templateMusic: '/admin/template-music',
  templateMusicNew: '/admin/template-music/new',
  templateMusicEdit: (id: string) => `/admin/template-music/${id}`,
  renderJobs: '/admin/render-jobs',
  renderJobDetail: (id: string) => `/admin/render-jobs/${id}`,
  payments: '/admin/payments',
  paymentDetail: (id: string) => `/admin/payments/${id}`,
  users: '/admin/users',
  userDetail: (id: string) => `/admin/users/${id}`,
  memberships: '/admin/memberships',
  membershipDetail: (id: string) => `/admin/memberships/${id}`,
  operations: '/admin/operations',
  audit: '/admin/audit',
  auditCustomer: (id: string) => `/admin/audit/customer/${id}`,
  auditRender: (id: string) => `/admin/audit/render/${id}`,
  auditPayment: (id: string) => `/admin/audit/payment/${id}`,
  auditMembership: (id: string) => `/admin/audit/membership/${id}`,
  auditDownload: (id: string) => `/admin/audit/download/${id}`,
  launchReadiness: '/admin/launch-readiness',
} as const;
